---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-coco-data
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 60Gi
  nfs:
    path: /exports/data
    server: 172.17.0.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: static-coco-data
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-checkpoints
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 60Gi
  nfs:
    path: /exports/checkpoints
    server: 172.17.0.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: static-checkpoints
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coco-data
  namespace: dino
spec:
  storageClassName: "static-coco-data"
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dino-checkpoints
  namespace: dino
spec:
  storageClassName: "static-checkpoints"
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
