---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysadmin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding-sysadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sysadmin
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: sysadmin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: sysadmin
type: kubernetes.io/service-account-token

